In [1]:
import pandas as pd
import numpy as np

In [2]:
def read_experiment_file(filename):
    metadata = {}
    data = []
    
    with open(filename, 'r') as file:
        lines = file.readlines()
    
    # Parse metadata
    data_start = None
    for i, line in enumerate(lines):
        if line.strip() == "":
            continue
        
        parts = line.split('\t')
        if len(parts) == 2 and not parts[0].replace('.', '', 1).isdigit():
            key, value = parts
            metadata[key.strip()] = value.strip()
        elif "Current / A" in parts[0]:
            data_start = i + 1
            break
    
    # Read numerical data
    if data_start is not None:
        for line in lines[data_start:]:
            values = line.split('\t')
            if len(values) == 3:
                try:
                    data.append([float(v) for v in values])
                except ValueError:
                    continue  # Skip malformed lines
    
    df = pd.DataFrame(data, columns=["Current (A)", "Voltage (uV)", "Time (s)"])
    
    return metadata, df

In [ ]:
filename = "data/Ic_Data.txt"  # Change this to your actual file path
metadata, df = read_experiment_file(filename)

print("Metadata:", metadata)
print("Data:")
print(df.head())

Metadata: {'Sample': '2mm tape', 'date': '07/01/2025', 'Temperature (K)': '77.00', 'Angle (deg.)': '0.000000', 'field / T': '0.000000'}
Data:
   Current (A)  Voltage (uV)  Time (s)
0    -0.022416     -1.681175     0.000
1    -0.022637     -1.692240     0.283
2    -0.023539     -1.706892     0.328
3     0.080704     -1.971687     0.415
4     0.100873     -1.813486     1.006


In [5]:
# Convert dataframe columns to NumPy arrays
current = df["Current (A)"].to_numpy()
voltage = df["Voltage (uV)"].to_numpy()
time = df["Time (s)"].to_numpy()

print(current[:5])  # Print first 5 values as a check
print(voltage[:5])
print(time[:5])

[-0.022416 -0.022637 -0.023539  0.080704  0.100873]
[-1.681175 -1.69224  -1.706892 -1.971687 -1.813486]
[0.    0.283 0.328 0.415 1.006]
